export const fetchJSON = (number) => (
  json.slice(0,number)
);

const json = [
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496085888/hyena.jpg",
  label: "A confident hyena"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496122169/warthog.jpg",
  label: "A hairy warthog"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496122168/lion.jpg",
  label: "A royal lion"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496085949/elephant.jpg",
  label: "An elegant elephant"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191630/bluewildebeest_nzdedf.jpg",
  label: "A lachrymose wildebeest"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191625/mandrill_tcuqme.jpg",
  label: "An impetuous mandrill"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191625/waterbuffalo_uuzrhs.jpg",
  label: "A stunned water buffalo"},
  { image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496085887/giraffe.jpg",
   label: "A majestic giraffe" },
  {image: "http://res.cloudinary.com/heab4q3lg/image/upload/v1496122122/ostrich.jpg",
  label: "A curious ostrich"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191625/howler-monkey_jhtsde.jpg",
  label: "An insensitive howler monkey"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191626/chimpanzee_ujfzey.jpg",
  label: "A mocking chimpanzee"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191625/gorilla_cfblh5.jpg",
  label: "A cautious gorilla"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191625/bonobo_qb20qq.jpg",
  label: "An attentive bonobo"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496192102/kudu2_rdvoyh.jpg",
  label: "A sensibly distant kudu"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191624/crocodile_hwryu3.jpg",
  label: "Didn't get close enough to ask"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191624/blackmamba_jvavg9.jpg",
  label: "I'm just going to hide in this tree"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191623/leopard_mxkxyb.jpg",
  label: "A determined leopard"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191623/rhino_fd54gv.jpg",
  label: "A disgruntled rhino"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191622/cheetah_ltp2mb.jpg",
  label: "A cheetah doing an owl impression"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191622/zebra_h5wiys.jpg",
  label: "A friendly pair of zebras"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191622/chameleon_gexrik.jpg",
  label: "The most fashionable one here"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496191623/africangreyparrot_ifhern.jpg",
  label: "A ruffled parrot"},
  {image: "http://res.cloudinary.com/heab4q3lg/image/upload/v1496191623/lemur_k8whq6.jpg",
  label: "A silly lemur"},
  {image: "https://res.cloudinary.com/heab4q3lg/image/upload/v1496193583/hippo_rjlwsv.jpg",
  label: "A domineering hippo"},
];

//refactor to sample JSON
